services:
  minio:
    image: docker.io/bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data:/bitnami/minio/data"
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password
